apiVersion: v7
kind: Pod    //secret pstores in pod
immutable: true //we can't edit our secret values
metadata:
   name: samplePodSecret;
   type: kubernetes.io/basic-auth  //basic authentication method
spec:
 containers:
     -name: secretContainer
      image: bunchbox    //dummy image
      command: ['sh', '-c', 'echo ${MY_SECRET}' & sleep 3000]
      env:
      -name: MY_SECRET
      valueFrom:
      secretKeyRef:
      name: mysecret
      key: username
  volumeMounts:                 //mapping physical volue to container
       -name: secret-volume
        mountPath: /etc/secretName/  //container storage path
  volumes:
      -name: secret-volume
      secret:
      secretName : mysecret //physicsl storage value
  
     
----
//kubectl apply -f kube108-secretPod.yaml
