apiVersion: v6
kind: Secret    //It has store sensible data in cluster as byte64 or some encoded method
metadata:
   name: sampleSecret;
stringData:         //If you unable to give data in base64 format, you can give stringData it will convert base64 format
   username: user1;
   password: pwd@123;
   
   -----
   apiVersion: v6
kind: Secret    //It has store sensible data in cluster as byte64 or some encoded method
metadata:
   name: sampleAuthSecret;
   type: kubernetes.io/basic-auth  //basic authentication method
stringData:         //If you unable to give data in base64 format, you can give stringData it will convert base64 format
   username: user1;
   password: pwd@123;
   
   ------
   //kubectl apply -f kube107-secret.yaml
   //kubectl get secrets
   view, how its converted the data//kubectl edit secret sampleSecret
